#!/usr/bin/env python3
"""Free problem-solving skill set for autonomous-github-agent
All tools local or free-tier. Expand this file to grow capabilities.
Covers: files, grep, tests, diffs, notifications, triage, releases, merges, python upgrades, actions.
"""
import os, re, json, subprocess, logging
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime

log = logging.getLogger("skills")

def skill_list_files(pattern: str = "**/*", root: str = ".") -> List[str]:
    return [str(p) for p in Path(root).glob(pattern) if p.is_file()][:200]

def skill_grep(pattern: str, path: str = ".") -> List[str]:
    hits = []
    for p in Path(path).rglob("*"):
        if p.is_file() and p.suffix in {".py", ".js", ".ts", ".md", ".yml", ".yaml", ".json"}:
            try:
                for i, line in enumerate(p.read_text(errors="ignore").splitlines(), 1):
                    if re.search(pattern, line):
                        hits.append(f"{p}:{i}:{line.strip()[:120]}")
                        if len(hits) >= 50: return hits
            except: pass
    return hits

def skill_run_tests(cmd: str = "pytest -q || npm test --silent || echo no-tests") -> Dict:
    try:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=120)
        return {"ok": r.returncode == 0, "code": r.returncode, "stdout": r.stdout[-2000:], "stderr": r.stderr[-1000:]}
    except Exception as e:
        return {"ok": False, "error": str(e)}

def skill_summarize_diff() -> str:
    try:
        return subprocess.check_output("git diff --stat HEAD~3 2>/dev/null || git status -s", shell=True, text=True)[:2000]
    except: return ""

def skill_mark_notifications_read(token: Optional[str] = None) -> int:
    token = token or os.getenv("GITHUB_TOKEN")
    if not token: return 0
    try:
        import requests
        headers = {"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3+json"}
        r = requests.get("https://api.github.com/notifications", headers=headers, params={"per_page": 50}, timeout=15)
        if not r.ok: return 0
        n = len(r.json())
        if n:
            requests.put("https://api.github.com/notifications", headers=headers,
                         json={"last_read_at": datetime.utcnow().isoformat()+"Z"}, timeout=15)
        return n
    except: return 0

def skill_triage_issue(title: str, body: str) -> Dict:
    text = (title + " " + body).lower()
    labels = []
    if any(k in text for k in ["bug", "error", "fail", "crash"]): labels.append("bug")
    if any(k in text for k in ["feat", "enhancement", "add "]): labels.append("enhancement")
    if any(k in text for k in ["doc", "readme"]): labels.append("documentation")
    if any(k in text for k in ["security", "vuln", "cve"]): labels.append("security")
    priority = "high" if "security" in labels or "critical" in text else "normal"
    return {"labels": labels or ["triage"], "priority": priority, "handled_by": "agent"}

def skill_list_branches() -> List[str]:
    try:
        out = subprocess.check_output("git branch -a --format='%(refname:short)'", shell=True, text=True)
        return [b.strip() for b in out.splitlines() if b.strip()]
    except: return []

def skill_merge_safe(branch: str, target: str = "main") -> Dict:
    """Attempt fast-forward or simple merge; abort on conflict (safe)."""
    try:
        subprocess.check_call(f"git checkout {target}", shell=True)
        r = subprocess.run(f"git merge --ff-only {branch}", shell=True, capture_output=True, text=True)
        if r.returncode == 0:
            return {"ok": True, "method": "ff-only", "branch": branch}
        r2 = subprocess.run(f"git merge --no-commit --no-ff {branch}", shell=True, capture_output=True, text=True)
        if r2.returncode != 0:
            subprocess.run("git merge --abort", shell=True)
            return {"ok": False, "error": "conflict", "stderr": r2.stderr[-500:]}
        subprocess.check_call(f"git commit -m 'merge: {branch} into {target} (agent)'", shell=True)
        return {"ok": True, "method": "no-ff", "branch": branch}
    except Exception as e:
        subprocess.run("git merge --abort 2>/dev/null", shell=True)
        return {"ok": False, "error": str(e)}

def skill_standard_release_name(version: str, prefix: str = "v") -> str:
    """Normalize release name to vX.Y.Z"""
    v = re.sub(r"[^0-9.]", "", version)
    parts = v.split(".")
    while len(parts) < 3: parts.append("0")
    return f"{prefix}{'.'.join(parts[:3])}"

def skill_create_release_notes(version: str) -> str:
    """Local free release notes from recent commits."""
    try:
        log = subprocess.check_output("git log -20 --pretty=format:'- %s (%h)'", shell=True, text=True)
        return f"# Release {version}\n\n## Changes\n{log}\n\nGenerated by autonomous-github-agent (free).\n"
    except:
        return f"# Release {version}\n\nAutomated release.\n"

def skill_python_upgrade_check(path: str = ".") -> Dict:
    """Report outdated packages (free, uses pip if available). Does not install."""
    try:
        r = subprocess.run("pip list --outdated --format=json 2>/dev/null", shell=True, capture_output=True, text=True)
        if r.returncode == 0 and r.stdout.strip():
            return {"outdated": json.loads(r.stdout)}
        return {"outdated": [], "note": "pip list --outdated not available or empty"}
    except Exception as e:
        return {"error": str(e)}

def skill_list_workflows() -> List[str]:
    """List GitHub Actions workflow files (local)."""
    return [str(p) for p in Path(".github/workflows").glob("*.yml")] + \
           [str(p) for p in Path(".github/workflows").glob("*.yaml")]

def skill_investigate_actions() -> Dict:
    """Lightweight free investigation of existing Actions."""
    files = skill_list_workflows()
    return {"workflows": files, "count": len(files), "note": "Inspect these for autonomous opportunities (free)"}

SKILLS = {
    "list_files": skill_list_files,
    "grep": skill_grep,
    "run_tests": skill_run_tests,
    "summarize_diff": skill_summarize_diff,
    "mark_notifications_read": skill_mark_notifications_read,
    "triage_issue": skill_triage_issue,
    "list_branches": skill_list_branches,
    "merge_safe": skill_merge_safe,
    "standard_release_name": skill_standard_release_name,
    "create_release_notes": skill_create_release_notes,
    "python_upgrade_check": skill_python_upgrade_check,
    "list_workflows": skill_list_workflows,
    "investigate_actions": skill_investigate_actions,
}

def available_skills() -> List[str]:
    return list(SKILLS.keys())

def run_skill(name: str, *args, **kwargs):
    if name not in SKILLS:
        return {"error": f"unknown skill {name}"}
    return SKILLS[name](*args, **kwargs)

if __name__ == "__main__":
    print("Available free skills:", available_skills())
