// This file was auto-generated by the Supabase integration tooling.
// Offline-mode support was added intentionally: when VITE_SUPABASE_URL /
// VITE_SUPABASE_PUBLISHABLE_KEY are unset, the app boots against a no-op
// stub client so it runs fully on local storage (see hybridDataManager).
// When the env vars ARE set, this module behaves exactly as before.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const isSupabaseConfigured: boolean = Boolean(
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
);

const OFFLINE_MESSAGE =
  'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable cloud sync.';

/**
 * Minimal no-op stand-in for the Supabase client, used only when the env
 * vars are missing. Every chained query builder is awaitable and resolves to
 * { data: null, error: Error }, so existing `const { data, error } = await
 * supabase.from(...).select()` call sites keep working and fall through to
 * their local/error paths. Realtime channel calls (.channel().on().subscribe(),
 * removeChannel) are harmless no-ops. The shared terminal object is frozen so
 * no call site can mutate shared state, and `error` is a real Error (not a
 * plain { message } object) so retry helpers short-circuit instead of burning
 * retries in demo mode.
 */
function createOfflineClient(): SupabaseClient<Database> {
  const terminal = Object.freeze({
    data: null,
    error: new Error(OFFLINE_MESSAGE),
  });
  const stub: any = new Proxy(function () {}, {
    get(_target: unknown, prop: string | symbol) {
      if (prop === 'then') {
        // Thenable: accept both handlers like a real promise. The offline
        // stub always resolves; the reject parameter is declared (not
        // silently dropped) so `.then(onFulfilled, onRejected)` behaves.
        return (
          resolve: (value: unknown) => void,
          reject: (reason?: unknown) => void
        ) => {
          void reject;
          resolve(terminal);
        };
      }
      if (prop === 'toString') return () => '[SupabaseOfflineClient]';
      if (prop === Symbol.toPrimitive) return () => '';
      if (typeof prop === 'symbol') return undefined;
      return stub;
    },
    apply() {
      return stub;
    },
  });
  return stub as SupabaseClient<Database>;
}

export const supabase: SupabaseClient<Database> = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createOfflineClient();
