#!/usr/bin/env node
/**
 * dependabot-check.mjs — read-only coverage check for .github/dependabot.yml.
 *
 * Validates that every tracked dependency manifest (package.json → npm,
 * requirements*.txt → pip) is covered by a matching package-ecosystem entry
 * (singular `directory:` or plural `directories:` list, exact or glob) in the
 * curated .github/dependabot.yml. The config is hand-curated (fleet schema:
 * groups, AGA-coordinator labels) — this tool only VERIFIES coverage, it never
 * rewrites the config.
 *
 * Coverage semantics (match real Dependabot behavior):
 *   - npm is recursive: one `directory:` entry covers every package.json at
 *     or below it (e.g. the root "/" entry covers all nested npm projects).
 *   - pip is NOT recursive: each requirements*.txt directory needs an exact
 *     or glob directory match.
 *
 * Skipped (not gaps):
 *   - AGA placeholders: manifests auto-generated by autonomous-github-agent
 *     carry an "Auto-generated placeholder" marker comment. Real dependencies
 *     remove the marker → coverage becomes enforced.
 *   - node_modules/** (never tracked, defensive)
 *   - mirror dirs whose runtime source of truth is the standalone repo
 *     (AGENTS.md "Fleet mirrors"): singularity-operator/, autonomous-github-agent/
 *
 * Modes:
 *   (default)   check; exit 1 when any manifest is uncovered
 *   --list      print the per-manifest coverage table, still exit 1 on gaps
 *   --help      usage
 *
 * Exit codes: 0 = all covered, 1 = gaps found, 2 = usage/infra error.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const CONFIG = path.join(ROOT, '.github', 'dependabot.yml');

// Standalone-repo mirror dirs (nested copies are NOT the source of truth).
const MIRROR_DIRS = ['singularity-operator/', 'autonomous-github-agent/'];

// Ecosystems where Dependabot recurses below a `directory:` entry — one entry
// covers every manifest at or beneath it. pip needs exact/glob dir matches.
const RECURSIVE_ECOSYSTEMS = new Set(['npm']);

// AGA scaffolding marker: manifests auto-generated by autonomous-github-agent
// ("Auto-generated placeholder — add project dependencies here") are skipped.
// Adding real dependencies removes the marker → coverage becomes enforced.
const PLACEHOLDER_MARKER = 'Auto-generated placeholder';

// Manifest → ecosystem mapping (extend as the fleet grows).
const ECOSYSTEM_RULES = [
  { test: (p) => path.posix.basename(p) === 'package.json', ecosystem: 'npm' },
  { test: (p) => /^requirements.*\.txt$/.test(path.posix.basename(p)), ecosystem: 'pip' },
];

function gitLsFiles() {
  const out = execFileSync('git', ['ls-files', '-z'], { cwd: ROOT, encoding: 'utf8' });
  return out.split('\0').filter(Boolean);
}

function normDir(d) {
  const s = String(d).trim().replace(/^["']|["']$/g, '').replace(/\/+$/, '');
  return s === '' ? '/' : s;
}

function globToRegex(glob) {
  const esc = glob
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*\*/g, '\0')
    .replace(/\*/g, '[^/]*')
    .replace(/\0/g, '.*');
  return new RegExp(`^${esc}$`);
}

/** Minimal line-based parser for the curated config (no YAML dep). */
function parseConfig(text) {
  const entries = [];
  let current = null;
  let inDirsList = false;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, '').replace(/\s+$/, '');
    const eco = line.match(/^\s*-\s*package-ecosystem:\s*["']?([\w-]+)["']?\s*$/);
    if (eco) {
      current = { ecosystem: eco[1], dirs: [] };
      entries.push(current);
      inDirsList = false;
      continue;
    }
    if (!current) continue;
    const single = line.match(/^\s*directory:\s*(\S+)\s*$/);
    if (single) { current.dirs.push(normDir(single[1])); inDirsList = false; continue; }
    if (/^\s*directories:\s*$/.test(line)) { inDirsList = true; continue; }
    if (inDirsList) {
      const item = line.match(/^\s*-\s*(\S+)\s*$/);
      if (item) { current.dirs.push(normDir(item[1])); continue; }
      inDirsList = false; // first non-item line ends the list
    }
  }
  return entries;
}

function covers(entries, ecosystem, dir) {
  for (const e of entries) {
    if (e.ecosystem !== ecosystem) continue;
    for (const d of e.dirs) {
      if (d === dir) return e;
      if (d.includes('*') && globToRegex(d).test(dir)) return e;
      if (RECURSIVE_ECOSYSTEMS.has(ecosystem)) {
        const prefix = d === '/' ? '/' : `${d}/`;
        if (dir.startsWith(prefix)) return e;
      }
    }
  }
  return null;
}

/**
 * Verdict over the inspected manifests.
 *
 * A run that inspected ZERO manifests must not report "all covered": `gaps`
 * would be empty and `gaps.length ? 1 : 0` would exit 0 - a green that means
 * "nothing was checked" rather than "everything is covered". That is an infra
 * condition (git enumeration or a rule table that matches nothing), so it exits 2
 * alongside the other infra failures, never 0.
 */
function summarize(rows) {
  if (!rows.length) {
    return { checked: 0, covered: 0, gaps: 0, exitCode: 2, reason: 'no manifests matched the ecosystem rules - nothing was checked' };
  }
  const gaps = rows.filter((r) => !r.hit).length;
  return { checked: rows.length, covered: rows.length - gaps, gaps, exitCode: gaps ? 1 : 0, reason: '' };
}

function runSelfTest() {
  const failures = [];
  let ran = 0;
  const check = (name, cond) => { ran += 1; if (!cond) failures.push(name); };

  // normDir
  check('empty normalizes to root', normDir('') === '/');
  check('trailing slash is stripped', normDir('/tools/') === '/tools');
  check('quotes are stripped', normDir('"/tools"') === '/tools');
  check('whitespace is trimmed', normDir('  /tools  ') === '/tools');

  // globToRegex - anchoring is what stops a prefix match faking coverage
  check('a single star does not cross a slash', globToRegex('/a/*').test('/a/b') === true);
  check('a single star does NOT match a nested path', globToRegex('/a/*').test('/a/b/c') === false);
  check('a double star crosses slashes', globToRegex('/a/**').test('/a/b/c') === true);
  check('a literal dot is not a regex wildcard', globToRegex('/a.b').test('/axb') === false);
  check('a literal dot matches itself', globToRegex('/a.b').test('/a.b') === true);
  check('a prefix is not a match (anchored)', globToRegex('/tools').test('/tools-extra') === false);

  // covers: npm recurses, pip does not
  const cfg = [{ ecosystem: 'npm', dirs: ['/app'] }, { ecosystem: 'pip', dirs: ['/py'] }];
  check('an exact dir is covered', covers(cfg, 'npm', '/app') !== null);
  check('npm recurses below its dir', covers(cfg, 'npm', '/app/sub') !== null);
  check('root dir covers everything below for npm', covers([{ ecosystem: 'npm', dirs: ['/'] }], 'npm', '/any/deep') !== null);
  check('a sibling dir is NOT covered', covers(cfg, 'npm', '/other') === null);
  check('pip does NOT recurse', covers(cfg, 'pip', '/py/sub') === null);
  check('the ecosystem must match', covers(cfg, 'pip', '/app') === null);
  check('a glob dir covers its match', covers([{ ecosystem: 'npm', dirs: ['/a/*'] }], 'npm', '/a/b') !== null);
  check('empty entries cover nothing', covers([], 'npm', '/') === null);

  // parseConfig
  const yaml = [
    'version: 2',
    'updates:',
    '  - package-ecosystem: "npm"',
    '    directories:',
    '      - "/app"',
    '      - /other',
    '    schedule:',
    '      interval: "weekly"',
    '  - package-ecosystem: pip',
    '    directory: "/py"',
  ].join('\n');
  const parsed = parseConfig(yaml);
  check('both ecosystems parse', parsed.length === 2);
  check('quoted dirs parse', parsed[0].dirs.includes('/app'));
  check('unquoted dirs parse', parsed[0].dirs.includes('/other'));
  check('a list ends at the first non-item line', !parsed[0].dirs.includes('interval:'));
  check('single-line directory parses', parsed[1].dirs.includes('/py'));
  check('comments are stripped', parseConfig('# - package-ecosystem: npm\n').length === 0);

  // summarize - the vacuous green this closes
  check('ZERO manifests exits 2, not 0', summarize([]).exitCode === 2);
  check('the zero-manifest reason is explicit', summarize([]).reason.length > 0);
  check('all covered exits 0', summarize([{ hit: true }, { hit: true }]).exitCode === 0);
  check('one gap exits 1', summarize([{ hit: true }, { hit: false }]).exitCode === 1);
  check('the gap count is right', summarize([{ hit: true }, { hit: false }]).gaps === 1);
  check('the covered count is right', summarize([{ hit: true }, { hit: false }]).covered === 1);
  check('an explicit-false row is a gap', summarize([{ hit: null }]).exitCode === 1);

  if (failures.length) {
    console.error(`dependabot-check self-test FAIL: ${failures.length} problem(s):`);
    for (const f of failures) console.error(`  FAIL  ${f}`);
    process.exit(1);
  }
  console.log(`dependabot-check self-test: ${ran}/${ran} passed`);
}

const args = process.argv.slice(2);
if (args.includes('--self-test')) {
  runSelfTest();
  process.exit(0);
}

function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) {
    console.log(
      [
        'dependabot-check.mjs - read-only coverage check for .github/dependabot.yml',
        '',
        'usage: node tools/dependabot-check.mjs [--list]',
        '',
        '  --list, -l  print the per-manifest coverage table (still exit 1 on gaps)',
        '  --help     print this text and exit 0',
  '  --self-test  prove coverage/glob/parse rules bite (no repo access needed)',
        '',
        'exit codes: 0 = all manifests covered, 1 = coverage gaps, 2 = usage/infra error.',
        'Unknown flags and unexpected arguments exit 2.',
      ].join('\n')
    );
    return 0;
  }
  // Round 12 D: a typo'd flag used to be silently ignored and the run still
  // exited 0/1, so CI could not tell "verified clean" from "never checked".
  const ALLOWED = new Set(['--list', '-l']);
  for (const a of args) {
    if (a === '--self-test') continue; // consumed before main(); keep the table accurate
    if (!a.startsWith('-')) {
      console.error(`dependabot-check: unexpected argument "${a}" - this tool takes flags only (see \`node tools/dependabot-check.mjs --help\`)`);
      return 2;
    }
    if (!ALLOWED.has(a)) {
      console.error(`dependabot-check: unknown flag "${a}" - see \`node tools/dependabot-check.mjs --help\``);
      return 2;
    }
  }
  const verbose = args.includes('--list') || args.includes('-l');

  if (!fs.existsSync(CONFIG)) {
    console.error('dependabot-check: .github/dependabot.yml not found');
    return 2;
  }
  const entries = parseConfig(fs.readFileSync(CONFIG, 'utf8'));
  if (!entries.length) {
    console.error('dependabot-check: no package-ecosystem entries parsed from dependabot.yml (parser drift?)');
    return 2;
  }

  const manifests = gitLsFiles()
    .map((f) => f.replace(/\\/g, '/'))
    .filter((f) => !f.includes('node_modules/'))
    .filter((f) => !MIRROR_DIRS.some((m) => f.startsWith(m)))
    .filter((f) => ECOSYSTEM_RULES.some((r) => r.test(f)));

  const rows = [];
  const placeholders = [];
  for (const f of manifests) {
    const rule = ECOSYSTEM_RULES.find((r) => r.test(f));
    let content = '';
    try { content = fs.readFileSync(path.join(ROOT, f), 'utf8'); } catch { /* raced deletion */ }
    if (content.includes(PLACEHOLDER_MARKER)) {
      placeholders.push({ file: f, ecosystem: rule.ecosystem });
      continue;
    }
    const parent = path.posix.dirname(f);
    const dir = parent === '.' ? '/' : normDir('/' + parent);
    rows.push({ file: f, ecosystem: rule.ecosystem, dir, hit: covers(entries, rule.ecosystem, dir) });
  }

  if (verbose) {
    for (const p of placeholders) {
      console.log(`skip ${p.ecosystem.padEnd(5)} ${'(AGA placeholder)'.padEnd(30)} ${p.file}`);
    }
    for (const r of rows) {
      console.log(`${r.hit ? 'ok  ' : 'GAP '} ${r.ecosystem.padEnd(5)} ${r.dir.padEnd(30)} ${r.file}`);
    }
  }

  const verdict = summarize(rows);
  const gapRows = rows.filter((r) => !r.hit);
  console.log(
    `dependabot-check: ${verdict.checked} manifests (${placeholders.length} skipped AGA placeholders), ` +
    `${verdict.covered} covered, ${verdict.gaps} uncovered (${entries.length} config entries)`
  );
  if (verdict.exitCode === 2 && !rows.length) {
    console.error(`dependabot-check: ${verdict.reason}`);
    return 2;
  }
  for (const p of placeholders) console.log(`  SKIP (AGA placeholder) ${p.file}`);
  for (const g of gapRows) console.error(`  GAP ${g.ecosystem} ${g.dir} <- ${g.file}`);
  if (verdict.gaps && process.env.GITHUB_ACTIONS === 'true') {
    for (const g of gapRows) {
      console.log(`::error file=${g.file}::manifest directory ${g.dir} not covered by .github/dependabot.yml`);
    }
  }
  return verdict.exitCode;
}

process.exit(main());
