#!/usr/bin/env node
/**
 * dependabot-check.mjs — read-only coverage check for .github/dependabot.yml.
 *
 * Validates that every tracked dependency manifest (package.json → npm,
 * requirements*.txt → pip) is covered by a matching package-ecosystem entry
 * (singular `directory:` or plural `directories:` list, exact or glob) in the
 * curated .github/dependabot.yml. The config is hand-curated (fleet schema:
 * groups, AGA-coordinator labels) — this tool only VERIFIES coverage, it never
 * rewrites the config.
 *
 * Coverage semantics (match real Dependabot behavior):
 *   - npm is recursive: one `directory:` entry covers every package.json at
 *     or below it (e.g. the root "/" entry covers all nested npm projects).
 *   - pip is NOT recursive: each requirements*.txt directory needs an exact
 *     or glob directory match.
 *
 * Skipped (not gaps):
 *   - AGA placeholders: manifests auto-generated by autonomous-github-agent
 *     carry an "Auto-generated placeholder" marker comment. Real dependencies
 *     remove the marker → coverage becomes enforced.
 *   - node_modules/** (never tracked, defensive)
 *   - mirror dirs whose runtime source of truth is the standalone repo
 *     (AGENTS.md "Fleet mirrors"): singularity-operator/, autonomous-github-agent/
 *
 * Modes:
 *   (default)   check; exit 1 when any manifest is uncovered
 *   --list      print the per-manifest coverage table, still exit 1 on gaps
 *   --help      usage
 *
 * Exit codes: 0 = all covered, 1 = gaps found, 2 = usage/infra error.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const CONFIG = path.join(ROOT, '.github', 'dependabot.yml');

// Standalone-repo mirror dirs (nested copies are NOT the source of truth).
const MIRROR_DIRS = ['singularity-operator/', 'autonomous-github-agent/'];

// Ecosystems where Dependabot recurses below a `directory:` entry — one entry
// covers every manifest at or beneath it. pip needs exact/glob dir matches.
const RECURSIVE_ECOSYSTEMS = new Set(['npm']);

// AGA scaffolding marker: manifests auto-generated by autonomous-github-agent
// ("Auto-generated placeholder — add project dependencies here") are skipped.
// Adding real dependencies removes the marker → coverage becomes enforced.
const PLACEHOLDER_MARKER = 'Auto-generated placeholder';

// Manifest → ecosystem mapping (extend as the fleet grows).
const ECOSYSTEM_RULES = [
  { test: (p) => path.posix.basename(p) === 'package.json', ecosystem: 'npm' },
  { test: (p) => /^requirements.*\.txt$/.test(path.posix.basename(p)), ecosystem: 'pip' },
];

function gitLsFiles() {
  const out = execFileSync('git', ['ls-files', '-z'], { cwd: ROOT, encoding: 'utf8' });
  return out.split('\0').filter(Boolean);
}

function normDir(d) {
  const s = String(d).trim().replace(/^["']|["']$/g, '').replace(/\/+$/, '');
  return s === '' ? '/' : s;
}

function globToRegex(glob) {
  const esc = glob
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*\*/g, '\0')
    .replace(/\*/g, '[^/]*')
    .replace(/\0/g, '.*');
  return new RegExp(`^${esc}$`);
}

/** Minimal line-based parser for the curated config (no YAML dep). */
function parseConfig(text) {
  const entries = [];
  let current = null;
  let inDirsList = false;
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/#.*$/, '').replace(/\s+$/, '');
    const eco = line.match(/^\s*-\s*package-ecosystem:\s*["']?([\w-]+)["']?\s*$/);
    if (eco) {
      current = { ecosystem: eco[1], dirs: [] };
      entries.push(current);
      inDirsList = false;
      continue;
    }
    if (!current) continue;
    const single = line.match(/^\s*directory:\s*(\S+)\s*$/);
    if (single) { current.dirs.push(normDir(single[1])); inDirsList = false; continue; }
    if (/^\s*directories:\s*$/.test(line)) { inDirsList = true; continue; }
    if (inDirsList) {
      const item = line.match(/^\s*-\s*(\S+)\s*$/);
      if (item) { current.dirs.push(normDir(item[1])); continue; }
      inDirsList = false; // first non-item line ends the list
    }
  }
  return entries;
}

function covers(entries, ecosystem, dir) {
  for (const e of entries) {
    if (e.ecosystem !== ecosystem) continue;
    for (const d of e.dirs) {
      if (d === dir) return e;
      if (d.includes('*') && globToRegex(d).test(dir)) return e;
      if (RECURSIVE_ECOSYSTEMS.has(ecosystem)) {
        const prefix = d === '/' ? '/' : `${d}/`;
        if (dir.startsWith(prefix)) return e;
      }
    }
  }
  return null;
}

function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) {
    console.log('usage: node tools/dependabot-check.mjs [--list]');
    return 0;
  }
  const verbose = args.includes('--list') || args.includes('-l');

  if (!fs.existsSync(CONFIG)) {
    console.error('dependabot-check: .github/dependabot.yml not found');
    return 2;
  }
  const entries = parseConfig(fs.readFileSync(CONFIG, 'utf8'));
  if (!entries.length) {
    console.error('dependabot-check: no package-ecosystem entries parsed from dependabot.yml (parser drift?)');
    return 2;
  }

  const manifests = gitLsFiles()
    .map((f) => f.replace(/\\/g, '/'))
    .filter((f) => !f.includes('node_modules/'))
    .filter((f) => !MIRROR_DIRS.some((m) => f.startsWith(m)))
    .filter((f) => ECOSYSTEM_RULES.some((r) => r.test(f)));

  const rows = [];
  const placeholders = [];
  for (const f of manifests) {
    const rule = ECOSYSTEM_RULES.find((r) => r.test(f));
    let content = '';
    try { content = fs.readFileSync(path.join(ROOT, f), 'utf8'); } catch { /* raced deletion */ }
    if (content.includes(PLACEHOLDER_MARKER)) {
      placeholders.push({ file: f, ecosystem: rule.ecosystem });
      continue;
    }
    const parent = path.posix.dirname(f);
    const dir = parent === '.' ? '/' : normDir('/' + parent);
    rows.push({ file: f, ecosystem: rule.ecosystem, dir, hit: covers(entries, rule.ecosystem, dir) });
  }

  if (verbose) {
    for (const p of placeholders) {
      console.log(`skip ${p.ecosystem.padEnd(5)} ${'(AGA placeholder)'.padEnd(30)} ${p.file}`);
    }
    for (const r of rows) {
      console.log(`${r.hit ? 'ok  ' : 'GAP '} ${r.ecosystem.padEnd(5)} ${r.dir.padEnd(30)} ${r.file}`);
    }
  }

  const gaps = rows.filter((r) => !r.hit);
  console.log(
    `dependabot-check: ${rows.length} manifests (${placeholders.length} skipped AGA placeholders), ` +
    `${rows.length - gaps.length} covered, ${gaps.length} uncovered (${entries.length} config entries)`
  );
  for (const p of placeholders) console.log(`  SKIP (AGA placeholder) ${p.file}`);
  for (const g of gaps) console.error(`  GAP ${g.ecosystem} ${g.dir} <- ${g.file}`);
  if (gaps.length && process.env.GITHUB_ACTIONS === 'true') {
    for (const g of gaps) {
      console.log(`::error file=${g.file}::manifest directory ${g.dir} not covered by .github/dependabot.yml`);
    }
  }
  return gaps.length ? 1 : 0;
}

process.exit(main());
