<# 
=====================================================================
review-repos.ps1
   Reviews the local git repo (monorepo) and its project subfolders.
   - Parent git repo: remote, branch, dirty/clean status
   - Each project subfolder: key files, file count (excluding deps)
=====================================================================
#>
# Workspace root
$WorkspaceRoot = Split-Path -Parent $PSScriptRoot

# --- Parent repo info ---
$remote = (git -C $WorkspaceRoot remote get-url origin 2>$null).Trim()
$branch = (git -C $WorkspaceRoot rev-parse --abbrev-ref HEAD 2>$null).Trim()
$statusShort = git -C $WorkspaceRoot status --short 2>$null
$dirty = -not [string]::IsNullOrWhiteSpace($statusShort)
$modified = @($statusShort | Where-Object { $_ -match '^ M|^M' }).Count
$untracked = @($statusShort | Where-Object { $_ -match '^\?\?' }).Count

# --- Project subfolders to review (ignore build/vendors) ---
$exclude = @('.git','node_modules','.venv','dist','build','AppData','.devcontainer','.docs','.vscode','.windsurf','.vexp','.github','.husky')
$projects = Get-ChildItem -Path $WorkspaceRoot -Directory | Where-Object {
    $exclude -notcontains $_.Name
}

$report = @()
$report += '# Local Repository Review (monorepo)'
$report += ''
$report += "> Reviewed $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
$report += ''
$report += "## Parent git repo"
$report += "- Root: $WorkspaceRoot"
$report += "- Remote: $remote"
$report += "- Branch: $branch"
$report += "- Status: $(if ($dirty) { "dirty ($modified modified, $untracked untracked)" } else { 'clean' })"
$report += ''
$report += '## Project subfolders'
$report += ''
$report += '| Project | Files* | package.json | requirements.txt | README | CI workflow |'
$report += '|---------|------:|:---:|:---:|:---:|:---:|'
foreach ($p in $projects) {
    $name = $p.Name
    $fc = (Get-ChildItem -Path $p.FullName -Recurse -File -ErrorAction SilentlyContinue | Where-Object {
        $_.FullName -notmatch '\\node_modules\\' -and $_.FullName -notmatch '\\.git\\' -and $_.FullName -notmatch '\\dist\\' -and $_.FullName -notmatch '\\build\\' -and $_.FullName -notmatch '\\.venv\\'
    } | Measure-Object).Count
    $hasPkg = Test-Path (Join-Path $p.FullName 'package.json')
    $hasReq = Test-Path (Join-Path $p.FullName 'requirements.txt')
    $hasReadme = @(Get-ChildItem -Path $p.FullName -Filter 'README*' -File -ErrorAction SilentlyContinue).Count -gt 0
    $hasCI = @(Get-ChildItem -Path $p.FullName -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.FullName -match '\\github\\workflows\\' }).Count -gt 0
    $report += "| $name | $fc | $(if ($hasPkg) { 'yes' } else { 'no' }) | $(if ($hasReq) { 'yes' } else { 'no' }) | $(if ($hasReadme) { 'yes' } else { 'no' }) | $(if ($hasCI) { 'yes' } else { 'no' }) |"
}
$report += ''
$report += '*file counts exclude node_modules/.git/dist/build/.venv'
$report += ''
$report += '> Generated by review-repos.ps1'
$output = $report -join "`n"
$outPath = Join-Path $WorkspaceRoot 'LocalRepoReview.txt'
Set-Content -Path $outPath -Value $output -Encoding UTF8
Write-Host "Review written to $outPath"